### ISSUE TITLE
Successful redirect from login page provides unauthorized access error

### ISSUE THREAD

**Issue by ajavorskidev** [Baby-Bubble-Pop/GraceShopper#57]
For bugs, please include the following:

* What is the expected behavior?
Once a user logs in, the user should stay logged in even after refreshing the page
* What is the actual behavior?
The user remains logged in initially after successful authentication, though after refreshing the page the user is signed off and error status 401 is received from the server.
* What steps reproduce the behavior?
By logging in with a 'user' role account
after successful authentication refresh the page in the browser
It will show you the login page, and the terminal will contain the error status 401
For features, please specify at least minimal requirements, e.g.:

* "As a user, I want a notification badge showing unread count, so I can easily manage my messages"
* "As a developer, I want linting to work properly with JSX, so I can see when there is a mistake"
* "As an admin, I want a management panel for users, so I can delete spurious accounts"

---

refactor the security middleware to allow users to get their own user information.

**Comment by jamesmannarino** [comment]
view linked pull request
